a_rtchat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('chat/', views.chat_view, name='chathome'),
    path('chat/<username>/', views.get_or_create_chatroom, name='start-chat'),
    path('chat/room/<chatroom_name>/',views.chat_view, name='chatroom' ),
    path('new/groupchat', views.create_groupchat, name="new-groupchat"),
    path('chat/edit/<chatroom_name>/', views.chatroom_edit_view, name='edit-chatroom'),
    path('chat/delete/<chatroom_name>/', views.chatroom_delete_view, name='chatroom-delete'),
    path('chat/leave/<chatroom_name>', views.chatroom_leave_view, name='chatroom-leave'),
    path('chat/add/<chatroom_name>', views.chatroom_add_view, name='chatroom-add'),
    #phan quyen admin chap nhan user vao nhom.
    path('chat/request_join/<str:chatroom_name>/', views.chat_view, name='request_join_chatroom'),
    path('chat/review_requests/<str:chatroom_name>/', views.review_join_requests, name='review_join_requests'),
    path('chat/handle_request/<request_id>/<action>/', views.handle_join_request, name='handle_join_request'),
    #gui file trong doan chat
    path('chat/fileupload/<chatroom_name>/', views.chat_file_upload, name="chat-file-upload"),
]

post/urls.py
from django.contrib import admin
from django.urls import path,include
from a_posts import views
urlpatterns = [
    path('', include('a_posts.urls')),
    path('', include('a_users.urls')),
    path('', include('a_rtchat.urls')),
    path('admin/', admin.site.urls),
]

a_rtchat/models.py
from django.db import models
from django.contrib.auth.models import User
import shortuuid
import uuid
import os
class ChatGroup(models.Model):
    group_name=models.CharField(max_length=128, unique=True,default=shortuuid.uuid)
    admin=models.ForeignKey(User,related_name='groupadmin', null=True, blank=True, on_delete=models.SET_NULL )
    groupchat_name=models.CharField(max_length=128, null=True, blank=True)
    users_online=models.ManyToManyField(User, related_name='online_in_groups', blank=True)
    members=models.ManyToManyField(User, related_name='chat_groups', blank=True)
    is_private=models.BooleanField(default=False)

    def __str__(self):
        return self.group_name
    

class GroupMessage(models.Model):
    group=models.ForeignKey(ChatGroup, related_name='chat_messages', on_delete=models.CASCADE)
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    body=models.CharField(max_length=300)
    file=models.FileField(upload_to='filemessage/', null=True, blank=True)
    created=models.DateTimeField(auto_now_add=True)

    @property
    def filename(self):
        if self.file:
            return os.path.basename(self.file.name)
        else :
            return None
    def __str__(self):
        if self.body:
            return f'{self.author.username}:{self.body}'
        elif self.file:
            return f'{self.author.username}:{self.file}'
    class Meta:
        ordering = ['-created']

    @property
    def is_image(self):
        if self.filename.lower().endswith(('.jpg', '.jpeg', '.png', '.gif', '.svg', '.webp')):
            return True
        else : 
            return False

class JoinRequest(models.Model):
    member = models.ForeignKey(User, on_delete=models.CASCADE, related_name="join_requests")
    chat_group = models.ForeignKey(ChatGroup, on_delete=models.CASCADE, related_name="join_requests")
    status = models.CharField(max_length=10, choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")], default="pending")
    created = models.DateTimeField(auto_now_add=True)
    request_name=models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    def __str__(self):
        return f"{self.member.username} - {self.chat_group.group_name} ({self.status})"
    
    class Meta:
        ordering=['-created']

a_rtchat/forms.py
from django.forms import ModelForm
from django import forms
from .models import *

class ChatmessageCreateForm(ModelForm):
    class Meta:
        model=GroupMessage
        fields=['body']
        widgets={
            'body': forms.TextInput(attrs={'placeholder': 'Add message...', 'class':'p-4 text-black', 'maxlength':'300', 'autofocus': True})

        }

class NewGroupForm(ModelForm):
    class Meta:
        model=ChatGroup
        fields=['groupchat_name']
        widgets={
            'groupchat_name': forms.TextInput(attrs={
                'placeholder': 'Add group name...',
                'class' : 'p-4 text-black',
                'maxlength': '300',
                'autofocus': True,
            })
        }

class ChatRoomEditForm(ModelForm):
    class Meta:
        model = ChatGroup
        fields = ['groupchat_name']
        widgets = {
            'groupchat_name' : forms.TextInput(attrs={
                'class': 'p-4 text-xl font-bold mb-4', 
                'maxlength' : '300', 
                }),
        }

class UserAddGroupChatForm(forms.Form):
    username = forms.CharField(
        max_length=150,
        required=True,
        label="username",
        widget=forms.TextInput(attrs={
            'class': 'p-4 text-xl font-bold mb-4',
            'maxlength': '300',
            'placeholder': 'Add a user...'
        })
    )

a_rtchat/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import *
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse
from .forms import *
from asgiref.sync import async_to_sync
from django.contrib import messages
from channels.layers import get_channel_layer

@login_required
def chat_view(request, chatroom_name='public-chat'):
    chat_group=get_object_or_404(ChatGroup,group_name=chatroom_name )
    chat_messages=chat_group.chat_messages.all()[:30]
    form = ChatmessageCreateForm()
    other_user=None
    if chat_group.is_private:
        if request.user not in chat_group.members.all():
            raise Http404()
        for member in chat_group.members.all():
            if request.user != member:
                other_user=member
                break

    # kiem tra xem noi nhom co ten nhom(groupchat_name): day la group ma mk tu tao ra
    if chat_group.groupchat_name:
        if request.user not in chat_group.members.all():
            # chat_group.members.add(request.user)
            # Nếu chưa là thành viên, kiểm tra nếu đã có yêu cầu tham gia hay chưa
            join_request, created = JoinRequest.objects.get_or_create(member=request.user, chat_group=chat_group)
            join_request.status='pending'
            join_request.save()

            if created:
                # Nếu yêu cầu mới được tạo, hiển thị thông báo xác nhận
                message = "Yêu cầu tham gia của bạn đã được gửi và đang chờ admin duyệt."
            else:
                # Nếu yêu cầu đã tồn tại, hiển thị thông báo chờ duyệt
                message = "Yêu cầu tham gia của bạn đang được xử lý."

            # Chuyển hướng hoặc hiển thị thông báo
            return render(request, 'partials/join_request_pending.html', {'message': message, 'chat_group': chat_group})


    if request.htmx:
        form=ChatmessageCreateForm(request.POST)
        if form.is_valid:
            message=form.save(commit=False)
            message.author=request.user
            message.group=chat_group
            message.save()
            context={
                'message': message,
                'user': request.user,
            }
            return render(request,'partials/chat_message_p.html', context)
    
    context={
        'chat_messages': chat_messages,
        'form': form,
        'other_user': other_user,
        'chatroom_name': chatroom_name,
        'chat_group':chat_group,
    }
        
    return render(request, 'a_rtchat/chat.html', context)


#ham nhan hoac tao phong tro chuyen cá nhân 1-1 giữa 2 người.
@login_required
def get_or_create_chatroom(request, username=None):
    
    if not username:
        return redirect('chathome')  # Nếu không có username, chuyển hướng về trang chủ trò chuyện
    
    if request.user.username == username:
        return redirect('chathome')

    other_user=get_object_or_404(User, username=username)

    # loc tat ca cac phong tro chuyen private ma nguoi dung nay la thanh vien.
    my_chatrooms=request.user.chat_groups.filter(is_private=True)

    if my_chatrooms.exists():
        for chatroom in my_chatrooms:
            if other_user in chatroom.members.all():
                chatroom=chatroom
                break
            else:
                chatroom=ChatGroup.objects.create(is_private=True)
                chatroom.members.add(request.user, other_user)

    else:
        chatroom=ChatGroup.objects.create(is_private=True)
        chatroom.members.add(request.user, other_user)
    return redirect('chatroom', chatroom.group_name)

#tạo 1 groupchat nhiều thành viên.
@login_required
def create_groupchat(request):
    form = NewGroupForm()
    
    if request.method == 'POST':
        form = NewGroupForm(request.POST)
        if form.is_valid():
            new_groupchat = form.save(commit=False)
            new_groupchat.admin = request.user
            new_groupchat.save()
            new_groupchat.members.add(request.user)
            return redirect('chatroom', new_groupchat.group_name)
    
    context = {
        'form': form
    }
    return render(request, 'partials/create_groupchat.html', context)

# ham chinh sua lai nhom chat: doi ten, xoa thanh vien, thuc hien chuc nang cua admin.
@login_required
def chatroom_edit_view(request, chatroom_name):
    chat_group=get_object_or_404(ChatGroup, group_name=chatroom_name)
    if request.user != chat_group.admin:
        raise Http404()
    form=ChatRoomEditForm(instance=chat_group)

    if request.method == "POST":
        form=ChatRoomEditForm(request.POST, instance=chat_group)
        if form.is_valid:
            form.save()

            #danh sach id cua cac thanh vien bi xoa khoi nhom chat
            remove_members=request.POST.getlist('remove_members')
            for member_id in remove_members:
                member=User.objects.get(id=member_id)
                chat_group.members.remove(member)

            return redirect('chatroom', chatroom_name)

    context={
        'form': form,
        'chat_group': chat_group,
    }
    return render(request, 'partials/chatroom_edit.html', context)

#ham xoa nhom chat
@login_required
def chatroom_delete_view(request, chatroom_name):
    chat_group=get_object_or_404(ChatGroup, group_name=chatroom_name)

    if request.user != chat_group.admin:
        raise Http404()
    
    if request.method == "POST":
        chat_group.delete()
        messages.success(request, 'Chatroom deleted')
        return redirect('login')
    
    return render(request, 'partials/chatroom_delete.html', {'chat_group':chat_group})

#admin them 1 nguoi dung vao trong nhom chat.
@login_required
def chatroom_add_view(request, chatroom_name):
    # Lấy nhóm chat theo `group_name`
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)

    # Kiểm tra quyền admin
    if request.user != chat_group.admin:
        raise Http404()
    
    form = UserAddGroupChatForm()
    if request.method == "POST":
        form = UserAddGroupChatForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            
            # Kiểm tra sự tồn tại của người dùng
            try:
                add_user = User.objects.get(username=username)
            except User.DoesNotExist:
                form.add_error('username', "Người dùng không tồn tại.")
            else:
                # Kiểm tra người dùng đã có trong nhóm chưa
                if add_user in chat_group.members.all():
                    form.add_error('username', "Người dùng đã là thành viên của nhóm.")
                else:
                    # Thêm người dùng vào nhóm
                    chat_group.members.add(add_user)
                    return redirect('chatroom', chat_group.group_name)
        
    # Trả về template nếu không phải phương thức POST hoặc nếu có lỗi trong form
    context = {
        'form': form,
        'chat_group': chat_group,
    }
    return render(request, 'partials/chatroom_add.html', context)


#khi 1 người dùng rời khỏi nhóm chat.
@login_required
def chatroom_leave_view(request, chatroom_name):
    chat_group=get_object_or_404(ChatGroup, group_name=chatroom_name)

    if request.user not in chat_group.members.all():
        raise Http404()

    if request.method == "POST":
        if request.user == chat_group.admin:
            # Lấy danh sách các thành viên khác (ngoại trừ admin hiện tại)
            other_members = chat_group.members.exclude(id=request.user.id)
            
            #xem danh sach co trong khong
            if other_members.exists():
                new_admin=other_members.first()
                chat_group.admin=new_admin
                chat_group.save()
                messages.success(request, f'new admin {new_admin.username}')
            #neu group trong
            else :
                #xoa nhom chat
                chat_group.delete()
                messages.success(request,"The group has been deleted because there are no more members")
            chat_group.members.remove(request.user)
        else:
            chat_group.members.remove(request.user)
            messages.success(request, 'You have left the chat')

        
        return redirect('login')
    
    return render(request, 'partials/chatroom_leave.html', {'chat_group':chat_group})



#admin duyet cac yeu cau tham gia nhom cua cac user.
@login_required
def review_join_requests(request, chatroom_name):
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)

    # Kiểm tra quyền admin
    if request.user != chat_group.admin:
        raise Http404("Bạn không có quyền quản lý nhóm này.")

    
    join_requests = chat_group.join_requests.filter(status="pending")

    context = {
        'join_requests': join_requests,
        'chat_group': chat_group,
    }
    return render(request, 'partials/review_join_requests.html', context)

#admin duyet cac yeu cau tham gia nhom cua cac user(đồng ý/ từ chối yêu cầu tham gia)
@login_required
def handle_join_request(request, request_id, action):
    join_request = get_object_or_404(JoinRequest, request_name=request_id)

    # Kiểm tra quyền admin của nhóm chat
    if request.user != join_request.chat_group.admin:
        raise Http404()

    if request.method == "POST":
        if action == "accept":
            join_request.status = "accepted"
            join_request.chat_group.members.add(join_request.member)  # Thêm thành viên vào nhóm
        elif action == "reject":
            join_request.status = "rejected"
        
        join_request.save()  # Lưu trạng thái mới
        join_request.delete()  # Xóa yêu cầu sau khi xử lý

    return redirect('review_join_requests', chatroom_name=join_request.chat_group.group_name)

#gửi tin nhắn dạng file trong đoạn chat.
@login_required
def chat_file_upload(request, chatroom_name):
    chat_group=get_object_or_404(ChatGroup, group_name=chatroom_name)

    if request.htmx and request.FILES:

templates/a_rtchat/chat.html
{% extends "layouts/blank.html" %}
{% block content %}
<wrapper class="block max-w-2xl mx-auto my-10 px-6">
    {% if chat_group.groupchat_name %}
    <div class="flex justify-between">
    <h2>{{chat_group.groupchat_name}}</h2>
    {% if user == chat_group.admin %}
    <a href="{% url 'edit-chatroom' chat_group.group_name %}">
        <div class="p-2 bg-gray-200 hover:bg-blue-600 rounded-lg group">
            <svg class="fill-gray-500 group-hover:fill-white" width="16" height="16">
                <path d="M11.013 1.427a1.75 1.75 0 0 1 2.474 0l1.086 1.086a1.75 1.75 0 0 1 0 2.474l-8.61 8.61c-.21.21-.47.364-.756.445l-3.251.93a.75.75 0 0 1-.927-.928l.929-3.25c.081-.286.235-.547.445-.758l8.61-8.61Zm.176 4.823L9.75 4.81l-6.286 6.287a.253.253 0 0 0-.064.108l-.558 1.953 1.953-.558a.253.253 0 0 0 .108-.064Zm1.238-3.763a.25.25 0 0 0-.354 0L10.811 3.75l1.439 1.44 1.263-1.263a.25.25 0 0 0 0-.354Z"></path>
            </svg>
        </div>
    </a>
    {% endif %}
    </div>
    {% endif %}
    <div id="chat_window" class="h-[45rem] flex flex-col bg-gray-800 rounded-2xl shadow-2xl relative p-1">
        <div class="flex justify-center text-emerald-400 bg-gray-800 p-2 sticky top-0 z-10">
            {% if other_user %}
            <div id="online-icon" class="gray-dot absolute top-2 left-2"></div>
            <a href="{% url 'userprofile' other_user.username %}">
                <div class="flex items-center gap-2 p-4 sticky top-0 z-10">
                    <img class="w-8 h-8 object-cover rounded-full" src="{{other_user.profile.avatar}}">
                    <div>
                        <span class="font-bold text-white">{{other_user.profile.name}}</span>
                        <span class="text-sm font-light text-gray-400">@{{other_user.username}}</span>
                    </div>
                </div>
            </a>
            {% elif chat_group.groupchat_name %}
            <ul id="groupchat-members" class="flex gap-4">
                {% for member in chat_group.members.all %}
                <li>
                    <a href="{% url 'userprofile' member.username %}" class="flex flex-col text-gray-400 items-center justify-center w-20 gap-2">
                        <img src="{{member.profile.avatar}}" class="w-14 h-14 rounded-full object-cover">
                        {{member.profile.name|slice:":10"}}
                    </a>
                </li>
                {% endfor %}

            </ul>
            {% else %}
                <div id="online-icon"></div>
                <span id="online-count" class="pr-1"></span>online
            {% endif %}
        </div>
        <div id='chat_container' class="overflow-y-auto grow">
            <ul id='chat_messages' class="flex flex-col justify-end gap-2 p-4">
                {% for message in chat_messages reversed %}
                    {% include 'partials/chat_message.html' %}
                {% endfor %}
                
            </ul>
        </div>
        <div class="sticky bottom-0 z-10 p-2 bg-gray-800">
            <div class="flex flex-col gap-4 items-center rounded-xl px-2 py-2">
                <form id="chat_message_form" class="w-full"
                hx-ext="ws"
                ws-connect="/ws/chatroom/{{chatroom_name}}"
                ws-send
                _="on htmx:wsAfterSend reset() me">
                    {% csrf_token %}
                    {{form}}
                </form>
                <form id="chat_file_form" enctype="multipart/form-data" class="flex items-center w-full" 
                    hx-post="{% url 'chat-file-upload' chat_group.group_name %}"
                    hx-target="#chat_messages"
                    hx-swap="beforeend" 
                    _="on htmx:beforeSend reset() me" >
                    {% csrf_token %}
                    <input type="file" name="file" id="id_file" class="!bg-transparent text-gray-400">
                    <button type="submit" class="whitespace-nowrap !text-sm !py-3 !px-4 h-fit">Submit File</button>
                </form>
            </div>
        </div>
    </div>
    {% if chat_group.members.exists %}
    <a href="{% url 'chatroom-leave' chat_group.group_name %}">Leave Chat</a>
    {% endif %}
</wrapper>
{% endblock content %}

<!--thanh cuon tu dong cuon xuong khi tin nhan moi duoc them vao trong doan chat-->
{% block javascript %}
<script>

    function scrollToBottom(time=0) {
        
        setTimeout(function() {
            const container = document.getElementById('chat_container');
            container.scrollTop = container.scrollHeight;
        }, time);
    }
    scrollToBottom()

</script>
{% endblock %}